WEB/find_your_rookie/find_your_rookie/background_setting/urls.py
from django.urls import path, include
from . import views

app_name = "background_setting"

urlpatterns = [
    path('', views.index, name='index'),
    path('back_setting/', views.back_setting, name='back_setting'),
    path('best11/', views.best11, name='best11'),
    path('ranking/', views.ranking, name='ranking'),
    path('international/', views.international, name='international'),
]

WEB/find_your_rookie/find_your_rookie/find_your_rookie/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('background_setting.urls')),
    # path('', views.index, name='index')
]

WEB/find_your_rookie/find_your_rookie/background_setting/models.py
from django.db import models


class offensive(models.Model):
    Rating = models.FloatField()
    name = models.CharField(max_length = 50)
    age = models.IntegerField()
    position1 = models.CharField(max_length = 20)
    Apps = models.CharField(max_length = 20)
    Mins = models.FloatField()
    Goals = models.FloatField()
    Assists = models.FloatField()
    SpG = models.FloatField()
    KeyP = models.FloatField()
    Drb = models.FloatField()
    Fouled = models.FloatField()
    Off = models.FloatField()
    Disp = models.FloatField()
    UnsTch = models.FloatField()
    
    def __str__(self):
        return f"{self.name}({self.age}/{self.position1})"
    
class defensive(models.Model):
    name = models.CharField(max_length = 50)
    age = models.IntegerField()
    position1 = models.CharField(max_length = 20)
    position2 = models.CharField(max_length = 20)
    Apps = models.CharField(max_length = 20)
    Mins = models.FloatField()
    Tackles = models.FloatField()
    Inter = models.FloatField()
    Fouls = models.FloatField()
    Offsides = models.FloatField()
    Clear = models.FloatField()
    Drb = models.FloatField()
    Blocks = models.FloatField()
    OwnG = models.FloatField()
    Rating = models.FloatField()
    def __str__(self):
        return f"{self.name}({self.age}/{self.position1},{self.position2})"

class passing(models.Model):
    name = models.CharField(max_length = 50)
    age = models.IntegerField()
    position1 = models.CharField(max_length = 20)
    position2 = models.CharField(max_length = 20)
    Apps = models.CharField(max_length = 20)
    Mins = models.FloatField()
    Assists = models.FloatField()
    KeyP = models.FloatField()
    AvgP = models.FloatField()
    PSpercent = models.FloatField()
    Crosses = models.FloatField()
    LongB = models.FloatField()
    ThrB = models.FloatField()
    Rating = models.FloatField()
    def __str__(self):
        return f"{self.name}({self.age}/{self.position1},{self.position2})"
    
# class Option(models.Model):
#     number = models.ExpressionList
    
# Create your models here.

WEB/find_your_rookie/find_your_rookie/background_setting/forms.py
from socket import fromshare
from django import forms

class ForwardForm(forms.Form):
    goals = forms.BooleanField(label='goals', required=False)
    SpG = forms.BooleanField(label='SpG', required=False)
    Drb = forms.BooleanField(label='Drb', required=False)
    Assists = forms.BooleanField(label='Assists', required=False)
    KeyP = forms.BooleanField(label='KeyP', required=False)
       
class MidfielderForm(forms.Form):
    PSper = forms.BooleanField(label='PS%', required=False)
    Crosses = forms.BooleanField(label='Crosses', required=False)
    LongB = forms.BooleanField(label='LongB', required=False)
    Assists = forms.BooleanField(label='Assists', required=False)
    KeyP_ThrB = forms.BooleanField(label='KeyP/ThrB', required=False)
    
class DefenderForm(forms.Form):
    Tackles = forms.BooleanField(label='Tackles', required=False)
    Interc = forms.BooleanField(label='Interc', required=False)
    Clear = forms.BooleanField(label='Clear', required=False)
    Blocks = forms.BooleanField(label='Blocks', required=False)
    Offsides = forms.BooleanField(label='Offsides', required=False)

WEB/find_your_rookie/find_your_rookie/background_setting/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
from .forms import ForwardForm, MidfielderForm, DefenderForm    
from django.views.generic import TemplateView
# Create your views here.
def index(request):
    return render(request, 'index.html')

def back_setting(request):
    
    # POST REQUSET --> CONFIRM THE FORM CONTENTS --> BACK TO HOMEPAGE
    # ELSE, RENDER FORM
    if request.method == 'POST':
        form = ForwardForm(request.POST)
        form2 = MidfielderForm(request.POST)
        form3 = DefenderForm(request.POST)
        
        if form.is_valid():
            print(form.cleaned_data)
            
        if form2.is_valid():
            print(form2.cleaned_data)
            
        if form3.is_valid():
            print(form3.cleaned_data)
            
    else:
        form = ForwardForm()
        form2 = MidfielderForm()
        form3 = DefenderForm()


    return render(request, 'background_setting/back_setting.html', {'form':form, 'form2':form2, 'form3':form3})
        

def best11(request):
    candidates = models.offensive.objects.all()
    context = {'candidates':candidates}
    return render(request, 'background_setting/best11.html', context=context)

def ranking(request):
    candidates = models.defensive.objects.all()
    context = {'candidates':candidates}
    return render(request, 'background_setting/ranking.html', context=context)

def international(request):
    candidates = models.defensive.objects.all()
    context={'candidates':candidates}
    return render(request, 'background_setting/international.html', context=context)

# def option(request):
#     if request.POST:
#         number = int(request.POST['goals'])
#         models.option.objects.create(list=number)
#         return redirect(reverse('templates:index'))
#     return render(request,index.html)
#  계획 : offensive/defensive/passing -> 3개의 카테고리에서 체크박스 번호를 넘겨받아서 번호별로 가중치 부여해서 rating 책정

WEB/find_your_rookie/find_your_rookie/find_your_rookie/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
# from . import models

def index(request):
    return render(request, 'index.html')

# def option(request):
#     if request.POST:
#         number = int(request.POST['goals'])
#         models.Option.objects.create(list=number)
#         # return redirect(reverse('find_your_rookie:index'))
#     return render(request, 'index.html')

WEB/find_your_rookie/find_your_rookie/background_setting/templates/background_setting/back_setting.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% load static %}
        <!-- Creative - Start Bootstrap Theme -->
        <title>Find Your Rookie</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <!-- <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav> -->
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Find Your Rookie!</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <form action="" method="POST">
                            {% csrf_token %}
                      <!--  <div class="text-white-75 mb-4">
                                <label class="text-white-75 mb-4">Forward(공격수)</label>
                                <input type="checkbox" name='forward' value='goals'>  goals  
                                <input type="checkbox" name='forward' value='SpG'>  SpG  
                                <input type="checkbox" name='forward' value='Drb'>  Drb  
                                <input type="checkbox" name='forward' value='Assists'>  Assists  
                                <input type="checkbox" name='forward' value='KeyP'>  KeyP 
                            </div><br>

                            <div class="text-white-75 mb-4">
                                <label class="text-white-75 mb-4">Midfielder(미드필더)</label>
                                <input type="checkbox" name='midfielder' value='PSper'>  PS%  
                                <input type="checkbox" name='midfielder' value='Crosses'>  Crosses  
                                <input type="checkbox" name='midfielder' value='LongB'>  LongB   
                                <input type="checkbox" name='midfielder' value='Assists'>  Assists  
                                <input type="checkbox" name='midfielder' value='KeyP_ThrB'>  KeyP/ThrB 
                            </div><br>

                            <div class="text-white-75 mb-4">
                                <label class="text-white-75 mb-4">Defender(수비수)</label>
                                <input type="checkbox" name='defender' value='Tackles'>  Tackles  
                                <input type="checkbox" name='defender' value='Interc'>  Interc  
                                <input type="checkbox" name='defender' value='Clear'>  Clear  
                                <input type="checkbox" name='defender' value='Blocks'>  Blocks  
                                <input type="checkbox" name='defender' value='Offsides'>  Offsides
                            </div><br> -->
                            <p>offensive option</p> 
                            {{form.as_table}}
                            <br>
                            <p>midfielder option</p> 
                            {{form2.as_table}}
                            <br>
                            <p>defensive option</p> 
                            {{form3.as_table}}
                            <br>
                            <input class="btn btn-primary btn-xl" type="submit"> 
                        </form>
                        <br>
                        <a class="btn btn-primary btn-xl" href="http://127.0.0.1:8000/">go back</a>
                        <!-- <input class='btn btn-primary' type="Save & Quit"> -->
                    </div>
                </div>
            </div>
        </header>
    </body>
</html>

WEB/find_your_rookie/find_your_rookie/background_setting/templates/background_setting/best11.html
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% load static %}
    <title>Find Your Rookie</title>
    <link href="{% static 'css/new.css' %}" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">Find Your Rookie</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/back_setting">SETTING</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/ranking">RANKING</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/international">INTERNATIONAL</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="masthead">
        <div class="lb-wrap">
            
            {%if candidates.index == 1 %}
                <div class="lb-st">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 2 %}
                <div class="lb-rw">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 3 %}
                <div class="lb-lw">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 4 %}
                <div class="lb-cm">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 5 %}
                <div class="lb-rm">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 6 %}
                <div class="lb-lm">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 7 %}
                <div class="lb-rwb">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 8 %}
                <div class="lb-rb">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 9 %}
                <div class="lb-lb">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%elif candidates.index == 10 %}
                <div class="lb-lwb">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%else%}
                <div class="lb-gk">
                    <h3>{{candidates.name}}}({{candidates.age}})</h3>
                </div>
            {%endif%}

            <!-- <div class="lb-st">
                <h3>benzema(age)</h3>
            </div>
            <div class="lb-rw">
                <h3>bale(age)</h3>
            </div>
            <div class="lb-lw">
                <h3>ronaldo(age)</h3>
            </div>
            <div class="lb-cm">
                <h3>modric(age)</h3>
            </div>
            <div class="lb-rm">
                <h3>casemiru(age)</h3>
            </div>
            <div class="lb-lm">
                <h3>kross(age)</h3>
            </div>
            <div class="lb-rwb">
                <h3>marcelo(age)</h3>
            </div>
            <div class="lb-rb">
                <h3>ramos(age)</h3>
            </div>
            <div class="lb-lb">
                <h3>varane(age)</h3>
            </div>
            <div class="lb-lwb">
                <h3>carbajal(age)</h3>
            </div>
            <div class="lb-gk">
                <h3>navas(age)</h3>
            </div> -->

            

            <div class="lb-image">
                <img src="{% static 'assets/img/best11-back2.jpg' %}" alt="">
            </div>
        </div>
    </header>
</body>
</html>

WEB/find_your_rookie/find_your_rookie/background_setting/templates/background_setting/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% load static %}
        <!-- Creative - Start Bootstrap Theme -->
        <title>Find Your Rookie</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <!-- <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav> -->
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Find Your Rookie!</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">2022년 카타르 월드컵에 출전하는 유망주 선수를 찾아보세요!<p>
                        You can download our original analysis source code => https://github.com </p>
                        <!-- <p class="text-white-75 mb-5">-Joy-</p> -->
                        <a class="btn btn-primary btn-xl" href="#about">START</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0"> Setting </h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">당신이 축구에서 중요하다고 생각하는 요소를 선택해주세요!</p>
                        <p class="text-white-75 mb-4">(선택을 완료하였으면 아래에서 원하는 서비스(이미지)를 골라주세요!)</p>
                        <a class="btn btn-light btn-xl" href="{% url 'background_setting:back_setting' %}">Get Started to Setting!</a> 
                    </div>
                </div>
            </div>
        </section>
        
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'background_setting:best11' %}" title="Project Name">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/best11.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-name">Best 11</div>
                                <div class="project-category text-white-50">당신이 선택한 옵션에 맞는 유망주를 Best 11로 추천해드립니다!</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'background_setting:ranking' %}" title="Project Name">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/ranking.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-name">Ranking(position)</div>
                                <div class="project-category text-white-50">당신이 선택한 옵션을 통해 포지션 별로 순위를 보여드립니다!</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'background_setting:international' %}" title="Project Name">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/inter.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-name">International Team(best 11)</div>
                                <div class="project-category text-white-50">당신이 선택한 옵션을 통해 국가별 Best 11을 보여드립니다!</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>           
    </body>
</html>

WEB/find_your_rookie/find_your_rookie/background_setting/templates/background_setting/test.html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>CSS</title>
		<style>
			.jb-wrap {
				width: 40%;
				margin: 10px auto;
				border: 1px solid #000000;
			}
			.jb-wrap img {
				width: 100%;
				vertical-align: middle;
			}
			.jb-text {
				padding: 5px 10px;
				background-color: yellow;
				text-align: center;
			}
		</style>
	</head>
	<body>
		<div class="jb-wrap">
			<div class="jb-image"><img src="images/400x300.png" alt=""></div>
			<div class="jb-text">
				<p>HELLO</p>
			</div>
		</div>
	</body>
</html>

WEB/find_your_rookie/find_your_rookie/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% load static %}
        <!-- Creative - Start Bootstrap Theme -->
        <title>Find Your Rookie</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <!-- <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav> -->
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Find Your Rookie!</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">2022년 카타르 월드컵에 출전하는 유망주 선수를 찾아보세요!<p>
                        You can download our original analysis source code => https://github.com </p>
                        <!-- <p class="text-white-75 mb-5">-Joy-</p> -->
                        <a class="btn btn-primary btn-xl" href="#about">START</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0"> Setting </h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">당신이 축구에서 중요하다고 생각하는 요소를 선택해주세요!</p>
                        <p class="text-white-75 mb-4">(선택을 완료하였으면 아래에서 원하는 서비스(이미지)를 골라주세요!)</p>
                        <a class="btn btn-light btn-xl" href="{% url 'background_setting:back_setting' %}">Get Started to Setting!</a> 
                    </div>
                </div>
            </div>
        </section>
        
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'background_setting:best11' %}" title="Project Name">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/best11.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-name">Best 11</div>
                                <div class="project-category text-white-50">당신이 선택한 옵션에 맞는 유망주를 Best 11로 추천해드립니다!</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'background_setting:ranking' %}" title="Project Name">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/ranking.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-name">Ranking(position)</div>
                                <div class="project-category text-white-50">당신이 선택한 옵션을 통해 포지션 별로 순위를 보여드립니다!</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'background_setting:international' %}" title="Project Name">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/inter.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-name">International Team(best 11)</div>
                                <div class="project-category text-white-50">당신이 선택한 옵션을 통해 국가별 Best 11을 보여드립니다!</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>        
    {%block content%}
    {%endblock%}    
    </body>
</html>